import { defaultWorkingCalendar } from "./scheduler";
import { migrateLegacyAppStateToWorkspace } from "./workspace-model";
import { AppState, Workspace } from "./types";

const now = new Date().toISOString();

export const emptyState: AppState = {
  project: {
    id: "project-empty",
    name: "",
    client: "",
    location: "",
    budget: "",
    startDate: "",
    endDate: "",
    status: "",
    progress: 0,
    description: "",
  },
  documents: [],
  wbs: {
    id: "",
    code: "",
    name: "",
    level: 0,
    type: "project",
    progress: 0,
    status: "not_started",
    children: [],
  },
  tasks: [],
  resources: [],
  allocations: [],
  risks: [],
  milestones: [],
  activities: [],
  insights: [],
  lastUpdatedAt: now,
};

export const seedState: AppState = {
  project: {
    id: "project-1",
    calendarId: "cal-standard",
    name: "Education City Infrastructure Development - Phase 1",
    client: "CGD Consulting",
    location: "Karachi, Pakistan (4800 Acres)",
    budget: "PKR 12.5 Billion",
    startDate: "2025-09-01",
    endDate: "2027-06-30",
    status: "In Progress",
    progress: 67,
    description:
      "Comprehensive infrastructure development including road networks, utility systems, drainage, electrical distribution, and communications infrastructure for the Education City project.",
  },
  documents: [
    {
      id: "doc-1",
      name: "Submission of Revised Work Program.pdf",
      type: "pdf",
      size: "2.4 MB",
      uploadDate: "2026-03-06T00:00:00.000Z",
      status: "completed",
      pageCount: 8,
      parsedData: {
        tasksExtracted: 48,
        resourcesFound: 12,
        milestonesIdentified: 5,
      },
    },
    {
      id: "doc-2",
      name: "Project Schedule Q1 2026.xlsx",
      type: "excel",
      size: "1.8 MB",
      uploadDate: "2026-03-01T00:00:00.000Z",
      status: "completed",
      parsedData: {
        tasksExtracted: 156,
        resourcesFound: 28,
        milestonesIdentified: 12,
      },
    },
  ],
  wbs: {
    id: "1",
    code: "1.0",
    name: "Education City Infrastructure Development",
    level: 0,
    type: "project",
    progress: 67,
    status: "in_progress",
    children: [
      {
        id: "1.1",
        code: "1.1",
        name: "Planning & Design",
        level: 1,
        type: "phase",
        progress: 100,
        status: "completed",
        children: [
          {
            id: "1.1.1",
            code: "1.1.1",
            name: "Site Assessment",
            level: 2,
            type: "deliverable",
            progress: 100,
            status: "completed",
            children: [
              {
                id: "1.1.1.1",
                code: "1.1.1.1",
                name: "Topographic Survey",
                level: 3,
                type: "work_package",
                progress: 100,
                status: "completed",
              },
              {
                id: "1.1.1.2",
                code: "1.1.1.2",
                name: "Soil Investigation",
                level: 3,
                type: "work_package",
                progress: 100,
                status: "completed",
              },
            ],
          },
        ],
      },
      {
        id: "1.2",
        code: "1.2",
        name: "Site Preparation",
        level: 1,
        type: "phase",
        progress: 100,
        status: "completed",
      },
      {
        id: "1.3",
        code: "1.3",
        name: "Infrastructure Construction",
        level: 1,
        type: "phase",
        progress: 72,
        status: "in_progress",
      },
      {
        id: "1.4",
        code: "1.4",
        name: "Landscaping & Finishing",
        level: 1,
        type: "phase",
        progress: 15,
        status: "not_started",
      },
      {
        id: "1.5",
        code: "1.5",
        name: "Project Closeout",
        level: 1,
        type: "phase",
        progress: 0,
        status: "not_started",
      },
    ],
  },
  tasks: [
    {
      id: "T1",
      name: "Topographic Survey",
      start: "2025-09-01",
      end: "2025-09-15",
      progress: 100,
      status: "completed",
      dependencies: [],
      isMilestone: false,
      isCritical: true,
      assigned: "Survey Team",
    },
    {
      id: "T2",
      name: "Soil Investigation",
      start: "2025-09-10",
      end: "2025-09-30",
      progress: 100,
      status: "completed",
      dependencies: ["T1"],
      isMilestone: false,
      isCritical: true,
      assigned: "Geotechnical Team",
    },
    {
      id: "T7",
      name: "Design Phase Approval",
      start: "2025-12-20",
      end: "2025-12-25",
      progress: 100,
      status: "completed",
      dependencies: ["T1", "T2"],
      isMilestone: true,
      isCritical: true,
      assigned: "Project Manager",
    },
    {
      id: "T10",
      name: "Primary Roads Construction",
      start: "2026-03-16",
      end: "2026-05-30",
      progress: 80,
      status: "in_progress",
      dependencies: ["T7"],
      isMilestone: false,
      isCritical: true,
      assigned: "Road Team A",
    },
    {
      id: "T12",
      name: "Water Supply System",
      start: "2026-03-20",
      end: "2026-05-25",
      progress: 90,
      status: "in_progress",
      dependencies: ["T10"],
      isMilestone: false,
      isCritical: true,
      assigned: "Utility Team A",
    },
    {
      id: "T13",
      name: "Sewerage System",
      start: "2026-04-01",
      end: "2026-06-10",
      progress: 75,
      status: "in_progress",
      dependencies: ["T12"],
      isMilestone: false,
      isCritical: false,
      assigned: "Utility Team B",
    },
    {
      id: "T15",
      name: "Electrical Network",
      start: "2026-05-01",
      end: "2026-07-15",
      progress: 70,
      status: "in_progress",
      dependencies: ["T13"],
      isMilestone: false,
      isCritical: true,
      assigned: "Electrical Team",
    },
    {
      id: "T18",
      name: "Testing & Commissioning",
      start: "2026-09-01",
      end: "2026-10-31",
      progress: 0,
      status: "not_started",
      dependencies: ["T15"],
      isMilestone: false,
      isCritical: true,
      assigned: "QC Team",
    },
  ],
  resources: [
    {
      id: "R1",
      name: "Ahmed Khan",
      role: "Senior Civil Engineer",
      type: "person",
      status: "allocated",
      capacity: 100,
      allocated: 85,
      costRate: 2500,
      rateBasis: "hour",
      scope: "project",
      projectId: "project-1",
      skills: ["Road Design", "AutoCAD", "Project Management"],
      email: "ahmed.khan@project.com",
      updatedAt: now,
    },
    {
      id: "R2",
      name: "Fatima Ali",
      role: "Project Manager",
      type: "person",
      status: "allocated",
      capacity: 100,
      allocated: 90,
      costRate: 3000,
      rateBasis: "hour",
      scope: "project",
      projectId: "project-1",
      skills: ["Stakeholder Management", "Risk Analysis", "Scheduling"],
      email: "fatima.ali@project.com",
      updatedAt: now,
    },
    {
      id: "R3",
      name: "Ayesha Siddiqui",
      role: "Environmental Engineer",
      type: "person",
      status: "available",
      capacity: 100,
      allocated: 40,
      costRate: 2200,
      rateBasis: "hour",
      scope: "project",
      projectId: "project-1",
      skills: ["EIA", "Environmental Compliance", "Monitoring"],
      email: "ayesha@project.com",
      updatedAt: now,
    },
    {
      id: "R4",
      name: "Excavator CAT 320",
      role: "Heavy Equipment",
      type: "equipment",
      status: "allocated",
      capacity: 100,
      allocated: 75,
      costRate: 5000,
      rateBasis: "hour",
      scope: "project",
      projectId: "project-1",
      skills: ["Excavation", "Earthworks"],
      email: "",
      updatedAt: now,
    },
  ],
  allocations: [
    {
      id: "A1",
      resourceId: "R1",
      taskId: "T10",
      taskName: "Primary Roads Construction",
      startDate: "2026-03-16",
      endDate: "2026-05-30",
      allocation: 60,
    },
    {
      id: "A2",
      resourceId: "R2",
      taskId: "T7",
      taskName: "Design Phase Approval",
      startDate: "2026-01-01",
      endDate: "2026-12-31",
      allocation: 90,
    },
  ],
  risks: [
    {
      id: "risk-1",
      title: "Weather Delays",
      severity: "high",
      description: "Monsoon weather could slow earthworks and road construction.",
      mitigation: "Pre-position materials and resequence weather-sensitive work.",
    },
    {
      id: "risk-2",
      title: "Equipment Availability",
      severity: "medium",
      description: "Primary excavator utilization is high and leaves little buffer.",
      mitigation: "Secure a backup rental unit for critical path activities.",
    },
  ],
  milestones: [
    { id: "M1", name: "Site Survey Completion", date: "2026-01-15", status: "completed" },
    { id: "M2", name: "Design Phase Approval", date: "2026-02-28", status: "completed" },
    { id: "M3", name: "Earthworks Start", date: "2026-03-15", status: "in_progress" },
    { id: "M4", name: "Utility Network Installation", date: "2026-05-01", status: "pending" },
  ],
  activities: [
    {
      id: "activity-1",
      action: "Task completed",
      detail: "Topographic Survey Report submitted",
      time: "2 hours ago",
      user: "Engineering Team",
      createdAt: now,
    },
    {
      id: "activity-2",
      action: "Document uploaded",
      detail: "Revised Work Program v2.1 uploaded",
      time: "5 hours ago",
      user: "Muhammad Ikram",
      createdAt: now,
    },
  ],
  insights: [
    {
      id: "insight-1",
      type: "risk",
      message: "Weather forecast indicates a two-week delay risk for earthworks.",
    },
    {
      id: "insight-2",
      type: "suggestion",
      message: "Consider reallocating two equipment units toward primary roads to protect the critical path.",
    },
    {
      id: "insight-3",
      type: "info",
      message: "Critical path currently runs through utility network completion and commissioning.",
    },
  ],
  lastUpdatedAt: now,
};

export function buildEmptyWorkspace(): Workspace {
  const cal = defaultWorkingCalendar();
  const st: AppState = {
    ...emptyState,
    project: { ...emptyState.project, id: "project-empty", calendarId: cal.id },
  };
  return migrateLegacyAppStateToWorkspace(st, [cal]);
}

export function buildSeedWorkspace(): Workspace {
  return migrateLegacyAppStateToWorkspace(seedState, [defaultWorkingCalendar()]);
}
