import { useState, useRef, useEffect } from 'react';
import {
  Send,
  Bot,
  User,
  Loader2,
  Sparkles,
  MessageSquare,
  Clock,
  AlertTriangle,
  CheckCircle,
  HelpCircle,
  Zap,
  RefreshCw,
  Copy,
  ThumbsUp,
  ThumbsDown,
  Mic,
  Square,
  Volume2
} from 'lucide-react';
import { useProjectData } from '@/context/ProjectDataContext';

interface Message {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
  type?: 'text' | 'data' | 'suggestion';
  sources?: { type: string; id: string; relevance: number }[];
  confidence?: number;
}

const suggestedQueries = [
  { icon: Clock, text: 'Current project status', query: 'What is the current status of the project based on the uploaded documents?' },
  { icon: AlertTriangle, text: 'Top risks', query: 'Identify the top risks in the current project state and suggest mitigations.' },
  { icon: CheckCircle, text: 'Progress report', query: 'Show me the progress of all ongoing tasks and key milestones.' },
  { icon: Sparkles, text: 'Resource optimization', query: 'How can we optimize resource allocation?' },
];

const initialMessages: Message[] = [
  {
    id: '1',
    role: 'assistant',
    content: `Hello! I'm your InfraMind Assistant for the Education City Infrastructure project. I can help you with:

• **Project Status** - Get real-time updates on tasks, phases, and milestones
• **Risk Analysis** - Identify and assess potential project risks
• **Resource Management** - Optimize team and equipment allocation
• **Timeline Questions** - Understand schedules and dependencies
• **Progress Reports** - Generate detailed project reports

What would you like to know?`,
    timestamp: new Date(),
    type: 'text',
  },
];

// Responses are generated by the backend (OpenAI) using the stored project state.

export default function AIAssistant() {
  const [messages, setMessages] = useState<Message[]>(initialMessages);
  const [inputValue, setInputValue] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const { askAi, transcribeAudio, synthesizeSpeech } = useProjectData();
  const [isRecording, setIsRecording] = useState(false);
  const recorderRef = useRef<MediaRecorder | null>(null);
  const chunksRef = useRef<BlobPart[]>([]);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSend = async () => {
    if (!inputValue.trim()) return;

    const userMessage: Message = {
      id: Date.now().toString(),
      role: 'user',
      content: inputValue,
      timestamp: new Date(),
    };

    setMessages(prev => [...prev, userMessage]);
    setInputValue('');
    setIsTyping(true);

    try {
      const response = await askAi(userMessage.content);
      const aiMessage: Message = {
        id: (Date.now() + 1).toString(),
        role: 'assistant',
        content: response.answer,
        timestamp: new Date(),
        confidence: response.confidence,
        sources: response.sources,
      };

      setMessages(prev => [...prev, aiMessage]);
    } catch (err) {
      const message = err instanceof Error ? err.message : 'AI request failed';
      setMessages(prev => [
        ...prev,
        {
          id: (Date.now() + 1).toString(),
          role: 'assistant',
          content: `Sorry, I couldn’t complete that request.\n\nError: ${message}`,
          timestamp: new Date(),
          confidence: 0.4,
        },
      ]);
    } finally {
      setIsTyping(false);
    }
  };

  const handleSuggestedQuery = (query: string) => {
    setInputValue(query);
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
  };

  const startRecording = async () => {
    const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
    const recorder = new MediaRecorder(stream);
    chunksRef.current = [];
    recorder.ondataavailable = (event) => chunksRef.current.push(event.data);
    recorder.onstop = async () => {
      const blob = new Blob(chunksRef.current, { type: 'audio/webm' });
      try {
        const result = await transcribeAudio(blob);
        setInputValue((prev) => `${prev} ${result}`.trim());
      } catch (error) {
        console.error(error);
      }
      stream.getTracks().forEach((track) => track.stop());
    };
    recorder.start();
    recorderRef.current = recorder;
    setIsRecording(true);
  };

  const stopRecording = () => {
    recorderRef.current?.stop();
    setIsRecording(false);
  };

  const speak = async (text: string) => {
    try {
      const audioBlob = await synthesizeSpeech(text);
      const url = URL.createObjectURL(audioBlob);
      const audio = new Audio(url);
      void audio.play();
    } catch (_error) {
      const utterance = new SpeechSynthesisUtterance(text);
      speechSynthesis.speak(utterance);
    }
  };

  return (
    <div className="h-full flex flex-col">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">InfraMind Assistant</h1>
          <p className="text-gray-500">Get instant answers about your project</p>
        </div>
        <div className="flex items-center gap-3">
          <span className="flex items-center gap-2 px-3 py-1.5 bg-green-100 text-green-700 text-sm font-medium rounded-full">
            <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></div>
            Online
          </span>
          <button
            onClick={() => setMessages(initialMessages)}
            className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
            title="Reset chat"
          >
            <RefreshCw className="w-5 h-5 text-gray-500" />
          </button>
        </div>
      </div>

      <div className="flex-1 bg-white rounded-xl shadow-sm border border-gray-100 flex flex-col overflow-hidden">
        <div className="p-4 border-b border-gray-100 bg-gradient-to-r from-blue-50 to-purple-50">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-gradient-to-br from-blue-500 to-purple-600 rounded-xl">
              <Bot className="w-5 h-5 text-white" />
            </div>
            <div>
              <h3 className="font-semibold text-gray-900">InfraMind Intelligence Engine</h3>
              <p className="text-xs text-gray-500">Powered by InfraMind AI • Context-aware project analysis</p>
            </div>
          </div>
        </div>

        {messages.length === 1 && (
          <div className="p-6 border-b border-gray-100 bg-gray-50">
            <p className="text-sm text-gray-600 mb-4">Suggested queries to get started:</p>
            <div className="grid grid-cols-2 gap-3">
              {suggestedQueries.map((suggestion, index) => {
                const Icon = suggestion.icon;
                return (
                  <button
                    key={index}
                    onClick={() => handleSuggestedQuery(suggestion.query)}
                    className="flex items-center gap-3 p-3 bg-white border border-gray-200 rounded-lg hover:border-blue-300 hover:bg-blue-50 transition-colors text-left"
                  >
                    <Icon className="w-5 h-5 text-blue-600" />
                    <span className="text-sm text-gray-700">{suggestion.text}</span>
                  </button>
                );
              })}
            </div>
          </div>
        )}

        <div className="flex-1 overflow-y-auto p-6 space-y-6">
          {messages.map((message) => (
            <div key={message.id} className={`flex gap-4 ${message.role === 'user' ? 'justify-end' : 'justify-start'}`}>
              {message.role === 'assistant' && (
                <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full flex items-center justify-center flex-shrink-0">
                  <Bot className="w-5 h-5 text-white" />
                </div>
              )}
              <div className={`max-w-2xl ${message.role === 'user' ? 'order-1' : ''}`}>
                <div className={`p-4 rounded-2xl ${
                  message.role === 'user'
                    ? 'bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-tr-sm'
                    : 'bg-gray-100 text-gray-800 rounded-tl-sm'
                }`}>
                  <div className="prose prose-sm max-w-none">
                    {message.content.split('\n').map((line, i) => {
                      if (line.startsWith('•') || line.startsWith('1.') || line.startsWith('2.') || line.startsWith('3.')) {
                        return <li key={i} className="ml-4">{line.replace(/^[•123]\s*/, '')}</li>;
                      }
                      if (line.startsWith('**') && line.endsWith('**')) {
                        return <p key={i} className="font-semibold">{line.replace(/\*\*/g, '')}</p>;
                      }
                      if (line.match(/^[📊⚠️🔴🟡✅⏳🔄💡👥⚡📅⏱️🔗📈]/) || line.match(/^[A-ZÀ-Ü][A-ZÀ-Ü\s&]+:/)) {
                        return <p key={i} className="font-medium">{line}</p>;
                      }
                      return <p key={i}>{line}</p>;
                    })}
                  </div>
                </div>
                <div className={`flex items-center gap-2 mt-2 ${message.role === 'user' ? 'justify-end' : ''}`}>
                  {message.role === 'assistant' && (
                    <>
                      <span className="text-xs text-gray-400">
                        {message.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                      </span>
                      {message.confidence && (
                        <span className="text-xs text-gray-400">
                          • Confidence: {(message.confidence * 100).toFixed(0)}%
                        </span>
                      )}
                      <button
                        onClick={() => copyToClipboard(message.content)}
                        className="p-1 hover:bg-gray-100 rounded transition-colors"
                      >
                        <Copy className="w-3 h-3 text-gray-400" />
                      </button>
                      <button
                        onClick={() => void speak(message.content)}
                        className="p-1 hover:bg-gray-100 rounded transition-colors"
                        title="Read aloud"
                      >
                        <Volume2 className="w-3 h-3 text-gray-400" />
                      </button>
                      <button className="p-1 hover:bg-gray-100 rounded transition-colors">
                        <ThumbsUp className="w-3 h-3 text-gray-400" />
                      </button>
                      <button className="p-1 hover:bg-gray-100 rounded transition-colors">
                        <ThumbsDown className="w-3 h-3 text-gray-400" />
                      </button>
                    </>
                  )}
                  {message.role === 'user' && (
                    <span className="text-xs text-gray-400">
                      {message.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    </span>
                  )}
                </div>
              </div>
              {message.role === 'user' && (
                <div className="w-10 h-10 bg-gradient-to-br from-gray-600 to-gray-700 rounded-full flex items-center justify-center flex-shrink-0">
                  <User className="w-5 h-5 text-white" />
                </div>
              )}
            </div>
          ))}

          {isTyping && (
            <div className="flex gap-4">
              <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full flex items-center justify-center">
                <Bot className="w-5 h-5 text-white" />
              </div>
              <div className="p-4 bg-gray-100 rounded-2xl rounded-tl-sm">
                <div className="flex items-center gap-2">
                  <Loader2 className="w-4 h-4 text-blue-600 animate-spin" />
                  <span className="text-sm text-gray-500">Analyzing project data...</span>
                </div>
              </div>
            </div>
          )}

          <div ref={messagesEndRef} />
        </div>

        <div className="p-4 border-t border-gray-100 bg-gray-50">
          <div className="flex items-center gap-4">
            <div className="flex-1 relative">
              <input
                type="text"
                value={inputValue}
                onChange={(e) => setInputValue(e.target.value)}
                onKeyPress={(e) => e.key === 'Enter' && handleSend()}
                placeholder="Ask about project status, risks, resources, timeline..."
                className="w-full px-4 py-3 pr-12 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              />
              <Sparkles className="absolute right-4 top-1/2 -translate-y-1/2 w-5 h-5 text-blue-500" />
            </div>
            <button
              onClick={handleSend}
              disabled={!inputValue.trim() || isTyping}
              className="px-6 py-3 bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-xl hover:opacity-90 disabled:opacity-50 disabled:cursor-not-allowed transition-opacity flex items-center gap-2"
            >
              <Send className="w-4 h-4" />
              Send
            </button>
            <button
              onClick={() => (isRecording ? stopRecording() : void startRecording())}
              className={`px-4 py-3 rounded-xl transition-colors flex items-center gap-2 ${
                isRecording ? 'bg-red-100 text-red-700' : 'bg-white border border-gray-200 text-gray-700'
              }`}
              title={isRecording ? 'Stop recording' : 'Start voice input'}
            >
              {isRecording ? <Square className="w-4 h-4" /> : <Mic className="w-4 h-4" />}
              {isRecording ? 'Stop' : 'Voice'}
            </button>
          </div>
          <p className="text-xs text-gray-400 mt-2 text-center">
            AI responses are generated from the stored project state and extracted document context. Verify critical outputs against documentation.
          </p>
        </div>
      </div>
    </div>
  );
}
